name: Playwright Tests with Caching
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      test-to-run:
        description: 'Add your npx code here'
        required: false
        default: 'npm run script:to:run'
        type: string
      workers:
        description: 'Number of workers to use'
        required: false
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
      browsers:
        description: 'browser to run tests on'
        required: false
        default: 'chromium'
        type: choice
        options:
          - 'chromium'
          - 'firefox'
          - 'webkit'
          - 'all'
      base-url:
        description: 'Base URL for tests'
        required: false
        default: ''
        type: string


jobs:
  run-playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Playwright browsers from cache or install if missing
        uses: ./.github/actions/

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          test-to-run: ${{ github.event.inputs.test-to-run || 'npm run script:to:run' }}
          workers: ${{ github.event.inputs.workers || '1' }}
          browsers: ${{ github.event.inputs.browsers || 'chromium' }}
        run: | 
          ${{env.test-to-run}} -- --workers=${{env.workers}} --project=${{env.browsers}} ${{github.event.inputs.base-url}} || npm run posttest
   
      - name: Upload allure report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-results
          path: allure-report/
          retention-days: 30

      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 30

  
      - name: Generate Test Results Summary
        if: always()
        run: |
          echo "## 🧪 Test Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Workflow**: ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Trigger Type**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## 📊 Artifacts Available" >> $GITHUB_STEP_SUMMARY
          echo "- **Playwright Report**: HTML test report" >> $GITHUB_STEP_SUMMARY
          echo "- **Test Results**: Screenshots, videos, traces" >> $GITHUB_STEP_SUMMARY
          echo "- **Allure Results**: Raw test data for reporting" >> $GITHUB_STEP_SUMMARY