name: Run playwright test cases with caching
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [build]
    types:
      - completed
  workflow_dispatch:
    inputs:
      test-to-run:
        description: 'Add your npx code here'
        required: false
        default: 'npm run test'
        type: string

jobs:
  run-playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Playwright browsers from cache or install if missing
        uses: ./.github/actions/

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          test-to-run: ${{ github.event.inputs.test-to-run || 'npm run test' }}
        run: | 
          ${{env.test-to-run}}
  
  Fetch-Playwright-Test-Results:
    needs: run-playwright-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload allure report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-results
          path: allure-report/
          retention-days: 30

      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 30
          
  run-snyk-scan:
    needs: Fetch-Playwright-Test-Results
    name: Snyk scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    

  run-sonarqube-scan:
    needs: Fetch-Playwright-Test-Results
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-zap-scan:
    needs: Fetch-Playwright-Test-Results
    name: Zap scan
    runs-on: ubuntu-latest
    steps:  
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        continue-on-error: true
        with:
          target: ${{ secrets.ZAP_TARGET_URL }}

  
  