name: Run playwright test cases with caching
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [build]
    types:
      - completed
  workflow_dispatch:
    inputs:
      test-to-run:
        description: 'Add your npx code here'
        required: false
        default: 'npm run script:to:run'
        type: string
      workers:
        description: 'Number of workers to use'
        required: false
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
      browsers:
        description: 'browser to run tests on'
        required: false
        default: 'chromium'
        type: choice
        options:
          - 'chromium'
          - 'firefox'
          - 'webkit'
          - 'all'
      base-url:
        description: 'Base URL for tests'
        required: false
        default: ''
        type: string


jobs:
  run-playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Playwright browsers from cache or install if missing
        uses: ./.github/actions/

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          test-to-run: ${{ github.event.inputs.test-to-run || 'npm run script:to:run' }}
          workers: ${{ github.event.inputs.workers || '1' }}
          browsers: ${{ github.event.inputs.browsers || 'chromium' }}
        run: | 
          ${{env.test-to-run}} -- --workers=${{env.workers}} --project=${{env.browsers}} ${{github.event.inputs.base-url}} || npm run posttest
   
      - name: Upload allure report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-results
          path: allure-report/
          retention-days: 30

      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 30
          
  run-snyk-scan:
    name: Snyk scan
    needs: run-playwright-test
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'tests/**') || contains(github.event.pull_request.changed_files, 'tests/**') }}
    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    

  run-sonarqube-scan:
    if: ${{ contains(github.event.head_commit.message, 'tests/') || contains(github.event.pull_request.changed_files, 'tests/') }}
    needs: run-playwright-test
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-zap-scan:
    needs: run-playwright-test
    name: Zap scan
    runs-on: ubuntu-latest
    steps:  
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        continue-on-error: true
        with:
          target: ${{ secrets.ZAP_TARGET_URL }}

  
  