name: Build code, run unit test, run SAST, SCA, DAST security scans for NodeJs App
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  Playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm
    - run: npm install
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps
    - name: Run Playwright tests
      run: npm run test

    - name: Upload allure report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        path: allure-report/
        retention-days: 30

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=dotnetgithubactionsorg
          -Dsonar.projectKey=dotnetgithubactionsproject
  security:
    runs-on: ubuntu-latest
    needs: Playwright-tests
    name: Run the SCA scan on the source code
    steps:
      - uses: actions/checkout@master
      - name: RunSnyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  zap_scan:
    runs-on: ubuntu-latest
    needs: security
    name: Run DAST scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://the-internet.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'