name: Optimized playwright test using docker
on: [push, pull_request]
jobs:
  run-dockerized-playwright-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run playwright test on docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/projectHome omarelbably/playwrightautomation sh -c "npm run test" 

      - name: Upload allure report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-results
          path: allure-report/
          retention-days: 30

      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 30