name: Build
on: [push, pull_request]
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Run playwright test on docker
        run: |
          docker run --rm omarelbably/playwrightautomation npx playwright test api --workers=1 